### ISSUE TITLE
`thread 'Compute Task Pool (2)' panicked at 'called `Option::unwrap()` on a `None` value'` when despawning entities

### ISSUE THREAD

**Issue by ndarilek** [dimforge/rapier#279]
Hello,

Using bevy_rapier from main and rapier2d alpha.1, I get the above error when despawning an entity. This seems distinct from dimforge/bevy_rapier#111 in that, when I used the fixed branch, those panics were replaced by Bevy system ordering issues. This issue only appeared after fixing those.

My game is in a private repo, and makes heavy use of sensor colliders for visibility. I'm wondering if it, as a larger example, is triggering issues that the smaller examples aren't encountering. If you'd like access, let me know and I can arrange it privately, along with steps on how to reproduce.

Thanks! Here's the full log:

```
thread 'Compute Task Pool (2)' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\rapier2d-0.12.0-alpha.1\src\data\component_set.rs:27:26
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\core\src\panicking.rs:107
   2: core::panicking::panic
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\core\src\panicking.rs:48
   3: enum$<core::option::Option<ref$<rapier2d::dynamics::rigid_body_components::RigidBodyIds> >, 1, 18446744073709551615, Some>::unwrap<ref$<rapier2d::dynamics::rigid_body_components::RigidBodyIds> >
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\option.rs:746
   4: rapier2d::data::component_set::ComponentSet::index<bevy_rapier2d::physics::rigid_body_component_set::RigidBodyComponentsSet,rapier2d::dynamics::rigid_body_components::RigidBodyIds>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\rapier2d-0.12.0-alpha.1\src\data\component_set.rs:27
   5: rapier2d::data::component_set::impl$1::index_bundle
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\rapier2d-0.12.0-alpha.1\src\data\component_set.rs:68
    6: rapier2d::geometry::narrow_phase::NarrowPhase::select_active_contacts<bevy_rapier2d::physics::rigid_body_component_set::RigidBodyComponentsSet>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\rapier2d-0.12.0-alpha.1\src\geometry\narrow_phase.rs:1065
   7: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::build_islands_and_solve_velocity_constraints<bevy_rapier2d::physics::rigid_body_component_set::RigidBodyComponentsSet,bevy_rapier2d::physics::collider_component_set::ColliderComponentsSet>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\rapier2d-0.12.0-alpha.1\src\pipeline\physics_pipeline.rs:203
   8: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::step_generic<bevy_rapier2d::physics::rigid_body_component_set::RigidBodyComponentsSet,bevy_rapier2d::physics::collider_component_set::ColliderComponentsSet>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\rapier2d-0.12.0-alpha.1\src\pipeline\physics_pipeline.rs:635
   9: bevy_rapier2d::physics::systems::step_world_system<ref$<bevy_rapier2d::physics::plugins::S> >
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\git\checkouts\bevy_rapier-26af51cff3486e5b\27c945f\src\physics\systems.rs:328
  10: core::ops::function::FnMut::call_mut<void (*)(bevy_ecs::system::commands::Commands,tuple$<bevy_ecs::system::system_param::Res<bevy_core::time::time::Time>,bevy_ecs::change_detection::ResMut<bevy_rapier2d::physics::resources::SimulationToRenderTime> >,tupl
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\ops\function.rs:150
  11: core::ops::function::impls::impl$3::call_mut<tuple$<bevy_ecs::system::commands::Commands,tuple$<bevy_ecs::system::system_param::Res<bevy_core::time::time::Time>,bevy_ecs::change_detection::ResMut<bevy_rapier2d::physics::resources::SimulationToRenderTime> 
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\ops\function.rs:269
  12: bevy_ecs::system::function_system::impl$34::run::call_inner<tuple$<>,bevy_ecs::system::commands::Commands,tuple$<bevy_ecs::system::system_param::Res<bevy_core::time::time::Time>,bevy_ecs::change_detection::ResMut<bevy_rapier2d::physics::resources::Simulat
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.6.0\src\system\function_system.rs:512
  13: bevy_ecs::system::function_system::impl$34::run<tuple$<>,void (*)(bevy_ecs::system::commands::Commands,tuple$<bevy_ecs::system::system_param::Res<bevy_core::time::time::Time>,bevy_ecs::change_detection::ResMut<bevy_rapier2d::physics::resources::Simulation
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.6.0\src\system\function_system.rs:515
  14: bevy_ecs::system::function_system::impl$7::run_unsafe<tuple$<>,tuple$<>,tuple$<bevy_ecs::system::commands::Commands,tuple$<bevy_ecs::system::system_param::Res<bevy_core::time::time::Time>,bevy_ecs::change_detection::ResMut<bevy_rapier2d::physics::resource
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.6.0\src\system\function_system.rs:442
  15: bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::generator$0
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.6.0\src\schedule\executor_parallel.rs:214
  16: core::future::from_generator::impl$1::poll<bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::generator$0>
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\future\mod.rs:80
  17: async_executor::impl$4::spawn::generator$0
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:144
  18: core::future::from_generator::impl$1::poll<async_executor::impl$4::spawn::generator$0>
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\future\mod.rs:80
  19: async_task::raw::RawTask<core::future::from_generator::GenFuture<async_executor::impl$4::spawn::generator$0>,tuple$<>,async_executor::impl$4::schedule::closure$0>::run<core::future::from_generator::GenFuture<async_executor::impl$4::spawn::generator$0>,tup
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\raw.rs:489
  20: core::future::from_generator::impl$1::poll<async_executor::impl$4::run::generator$0::generator$0>
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\future\mod.rs:80
  21: futures_lite::future::impl$12::poll
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:529
  22: async_executor::impl$4::run::generator$0
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:242
  23: core::future::from_generator::impl$1::poll<async_executor::impl$4::run::generator$0>
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\future\mod.rs:80
  24: futures_lite::future::block_on::closure$0
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:89
  25: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::try_with
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\thread\local.rs:399
  26: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure$0,enum$<core::result::Result<tuple$<>,
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\thread\local.rs:375
  27: futures_lite::future::block_on
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:79
  28: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.6.0\src\task_pool.rs:139
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'task has failed', C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\task.rs:368:45
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\core\src\panicking.rs:107
   2: core::panicking::panic_display<str>
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\core\src\panicking.rs:63
   3: core::option::expect_failed
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\core\src\option.rs:1637
   4: core::option::Option::expect
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\option.rs:709
   5: async_task::task::impl$7::poll<tuple$<> >
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\task.rs:371
   6: bevy_tasks::task_pool::impl$2::scope::closure$0::generator$0
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.6.0\src\task_pool.rs:194
   7: core::future::from_generator::impl$1::poll<bevy_tasks::task_pool::impl$2::scope::closure$0::generator$0>
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\future\mod.rs:80
   8: core::future::future::impl$1::poll<ref_mut$<dyn$<core::future::future::Future,assoc$<Output,alloc::vec::Vec<tuple$<>,alloc::alloc::Global> > > > > >
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\future\future.rs:119
   9: async_executor::impl$9::spawn::generator$0<alloc::vec::Vec<tuple$<>,alloc::alloc::Global>,core::pin::Pin<ref_mut$<dyn$<core::future::future::Future,assoc$<Output,alloc::vec::Vec<tuple$<>,alloc::alloc::Global> > > > > > >
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:376
  10: core::future::from_generator::impl$1::poll<async_executor::impl$9::spawn::generator$0>
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\future\mod.rs:80
  11: async_task::raw::RawTask<core::future::from_generator::GenFuture<async_executor::impl$9::spawn::generator$0>,alloc::vec::Vec<tuple$<>,alloc::alloc::Global>,async_executor::impl$9::schedule::closure$0>::run<core::future::from_generator::GenFuture<async_exe
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\raw.rs:489
  12: async_executor::Executor::try_tick
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:181
  13: async_executor::LocalExecutor::try_tick
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:405
  14: bevy_tasks::task_pool::impl$2::scope::closure$0
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.6.0\src\task_pool.rs:223
  15: std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\thread\local.rs:399
  16: std::thread::local::LocalKey<async_executor::LocalExecutor>::with
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\thread\local.rs:375
  17: bevy_tasks::task_pool::TaskPool::scope<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure$1,tuple$<> >
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.6.0\src\task_pool.rs:169
  18: bevy_ecs::schedule::executor_parallel::impl$1::run_systems
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.6.0\src\schedule\executor_parallel.rs:122
  19: bevy_ecs::schedule::stage::impl$1::run
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.6.0\src\schedule\stage.rs:850
  20: bevy_ecs::schedule::Schedule::run_once
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.6.0\src\schedule\mod.rs:344
  21: bevy_ecs::schedule::impl$1::run
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.6.0\src\schedule\mod.rs:362
  22: bevy_app::app::App::update
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.6.0\src\app.rs:112
  23: bevy_winit::winit_runner_with::closure$1
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.6.0\src\lib.rs:504
  24: winit::platform_impl::platform::event_loop::impl$2::run_return::closure$0<tuple$<>,bevy_winit::winit_runner_with::closure$1>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:206
  25: alloc::boxed::impl$45::call_mut
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\alloc\src\boxed.rs:1701
  26: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:245
  27: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0>
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\panic\unwind_safe.rs:271
  28: std::panicking::try::do_call
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\panicking.rs:406
  29: std::panicking::try
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\panicking.rs:370
  30: std::panic::catch_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\panic.rs:133
  31: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:152
  32: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::call_event_handler<tuple$<> >
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:239
  33: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::move_state_to<tuple$<> >
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:297
  34: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::main_events_cleared
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:227
  35: winit::platform_impl::platform::event_loop::flush_paint_messages
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:726
  36: winit::platform_impl::platform::event_loop::thread_event_target_callback::closure$0
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:2091
  37: core::ops::function::FnOnce::call_once
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\ops\function.rs:227
  38: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure$0>
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\panic\unwind_safe.rs:271
  39: std::panicking::try::do_call
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\panicking.rs:406
  40: std::panicking::try
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\panicking.rs:370
  41: std::panic::catch_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\std\src\panic.rs:133
  42: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure$0>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:152
  43: winit::platform_impl::platform::event_loop::thread_event_target_callback<tuple$<> >
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:2271
  44: CallWindowProcW
  45: DispatchMessageW
  46: SendMessageTimeoutW
  47: KiUserCallbackDispatcher
  48: NtUserDispatchMessage
  49: DispatchMessageW
  50: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run_return<tuple$<>,bevy_winit::winit_runner_with::closure$1>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:221
  51: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run<tuple$<>,bevy_winit::winit_runner_with::closure$1>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:191
  52: winit::event_loop::EventLoop<tuple$<> >::run<tuple$<>,bevy_winit::winit_runner_with::closure$1>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\event_loop.rs:154
  53: bevy_winit::run<bevy_winit::winit_runner_with::closure$1>
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.6.0\src\lib.rs:171
  54: bevy_winit::winit_runner_with
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.6.0\src\lib.rs:513
  55: bevy_winit::winit_runner
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.6.0\src\lib.rs:211
  56: core::ops::function::Fn::call<void (*)(bevy_app::app::App),tuple$<bevy_app::app::App> >
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\ops\function.rs:70
  57: alloc::boxed::impl$46::call
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\alloc\src\boxed.rs:1708
  58: bevy_app::app::App::run
             at C:\Users\Nolan\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.6.0\src\app.rs:130
  59: system_fault::main
             at .\src\lib.rs:60
  60: main::main
             at .\src\bin\main.rs:4
  61: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\library\core\src\ops\function.rs:227
```

**Comment by sebcrozet** [comment]
Fixed in Rapier v0.12.0 (non-alpha version). Please reopen if the problem persists.
