### ISSUE TITLE
Panics in SAPAxis

### ISSUE THREAD

**Issue by ricochet1k** [dimforge/rapier#349]
Using rapier2d version 0.13.0 in a fairly simple Bevy game, it crashes after a while, sometimes only a few seconds sometimes after minutes. The crashes are in different places, here are some sample backtraces:

```
thread 'main' panicked at 'proxy.aabb.maxs 3.6 (in AABB { mins: [3.5858302, 1.4537827], maxs: [3.6, 1.471331] }) >= min_bound 3.6000001', /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_axis.rs:61:13
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rapier2d::geometry::broad_phase_multi_sap::sap_axis::SAPAxis::batch_insert
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_axis.rs:61:13
   3: rapier2d::geometry::broad_phase_multi_sap::sap_region::SAPRegion::update
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_region.rs:235:13
   4: rapier2d::geometry::broad_phase_multi_sap::sap_layer::SAPLayer::update_regions
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_layer.rs:306:17
   5: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::update_layers_and_find_pairs
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:551:13
   6: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::update
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:487:9
   7: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::detect_collisions
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/pipeline/physics_pipeline.rs:98:9
   8: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::step
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/pipeline/physics_pipeline.rs:527:13
   9: bevy_rapier2d::plugin::context::RapierContext::step_simulation
             at /Users/matt/code/bevy_rapier/bevy_rapier2d/../src/plugin/context.rs:202:21
  10: bevy_rapier2d::plugin::systems::step_simulation
```

```
thread 'main' panicked at 'attempt to subtract with overflow', /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_region.rs:190:17
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: rapier2d::geometry::broad_phase_multi_sap::sap_region::SAPRegion::update_after_subregion_removal
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_region.rs:190:17
   4: rapier2d::geometry::broad_phase_multi_sap::sap_layer::SAPLayer::complete_removals
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_layer.rs:341:21
   5: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::complete_removals
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:200:17
   6: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::update
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:491:9
   7: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::detect_collisions
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/pipeline/physics_pipeline.rs:98:9
   8: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::step
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/pipeline/physics_pipeline.rs:403:9
```

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `355`,
 right: `1333`', /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_layer.rs:162:17
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:182:5
   4: rapier2d::geometry::broad_phase_multi_sap::sap_layer::SAPLayer::unregister_subregion
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_layer.rs:162:17
   5: rapier2d::geometry::broad_phase_multi_sap::sap_layer::SAPLayer::complete_removals
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_layer.rs:353:29
   6: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::complete_removals
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:200:17
   7: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::update
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:491:9
   8: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::detect_collisions
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/pipeline/physics_pipeline.rs:98:9
   9: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::step
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/pipeline/physics_pipeline.rs:527:13
```

**Comment by sebcrozet** [comment]
Hi! Would it be possible for you to share your code so I can run it? This bug has been reported (on discord) for a while but I never found a way to reproduce it.

**Comment by sebcrozet** [comment]
A attempted a fix for this, please reopen if the problem persists.

**Comment by ricochet1k** [comment]
I don't have permission to reopen this issue, but it's still happening. I invited you as a collaborator on the project, you should be able to run it with the command in the Readme. It usually fails after a few minutes.

```
   Compiling rapier2d v0.13.0 (https://github.com/dimforge/rapier.git#77a4bbf1)
```

```
thread 'main' panicked at 'proxy.aabb.maxs 3.6 (in AABB { mins: [-4.4059176, 3.5826468], maxs: [-4.391378, 3.6] }) >= min_bound 3.6000001', /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_axis.rs:61:13
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rapier2d::geometry::broad_phase_multi_sap::sap_axis::SAPAxis::batch_insert
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_axis.rs:61:13
   3: rapier2d::geometry::broad_phase_multi_sap::sap_region::SAPRegion::update
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_region.rs:233:17
   4: rapier2d::geometry::broad_phase_multi_sap::sap_layer::SAPLayer::update_regions
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_layer.rs:306:17
   5: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::update_layers_and_find_pairs
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:551:13
   6: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::update
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:487:9
   7: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::detect_collisions
```

**Comment by ricochet1k** [comment]
Here's another different one: 
```
thread 'main' panicked at 'attempt to subtract with overflow', /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_region.rs:190:17
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: rapier2d::geometry::broad_phase_multi_sap::sap_region::SAPRegion::update_after_subregion_removal
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_region.rs:190:17
   4: rapier2d::geometry::broad_phase_multi_sap::sap_layer::SAPLayer::complete_removals
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/sap_layer.rs:341:21
   5: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::complete_removals
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:200:17
   6: rapier2d::geometry::broad_phase_multi_sap::broad_phase::BroadPhase::update
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/geometry/broad_phase_multi_sap/broad_phase.rs:491:9
   7: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::detect_collisions
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/pipeline/physics_pipeline.rs:98:9
   8: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::step
             at /Users/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.13.0/src/pipeline/physics_pipeline.rs:403:9
```

**Comment by sebcrozet** [comment]
Thank you! I’ll take a look.

**Comment by sebcrozet** [comment]
@ricochet1k I tried your code. Note that the way your `Cargo.toml` is setup, you won’t be using the github version of `rapier`. With this:
```toml
[dependencies]
bevy_rapier2d = { git = "https://github.com/dimforge/bevy_rapier.git", features = ["parallel", "simd-stable"] }
rapier2d = { git = "https://github.com/dimforge/rapier.git" }
```
the `bevy_rapier2d` crate will still depend on the `crates.io` version of `rapier2d`. (So the compiler will compile both the `crates.io` version and `github` version of `rapier2d`, but only the `crates.io` version will actually be used.) In order to make it use the `github` version of `rapier2d`, you need something like this:

```toml
[dependencies]
bevy_rapier2d = { version = "0.14", features = ["parallel", "simd-stable"]  }

[patch.crates-io]
bevy_rapier2d = { git = "https://github.com/dimforge/bevy_rapier.git" }
rapier2d = { git = "https://github.com/dimforge/rapier.git" }
```

With that change to the `Cargo.toml` I wasn’t able to reproduce the bug, would you mind testing again please?
