### ISSUE TITLE
Character controller crashes immediately on any input

### ISSUE THREAD

**Issue by darthdeus** [dimforge/rapier#414]
To reproduce (at current `master` - 506f911, which is the v0.16.0 release):

- run the 2d examples
- select "Character Controller"
- press A or D
- crash

```
$ RUST_BACKTRACE=1 cargo run --bin all_examples2
    Finished dev [optimized + debuginfo] target(s) in 0.14s
     Running `target/debug/all_examples2`
2022-11-06T02:08:43.211995Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.1354166666666667
2022-11-06T02:08:43.247028Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3060", vendor: 4318, device: 9476, device_type: DiscreteGpu, backend: Vulkan }
2022-11-06T02:08:43.302282Z  INFO rapier_testbed2d::lines: Loaded 2d debug lines plugin.
thread 'main' panicked at 'No element at index', crates/rapier_testbed2d/../../src_testbed/testbed.rs:705:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/core/src/option.rs:1880:5
   5: core::option::Option<T>::expect
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/core/src/option.rs:738:21
   6: <rapier2d::data::arena::Arena<T> as core::ops::index::Index<rapier2d::data::arena::Index>>::index
             at ./crates/rapier2d/../../src/data/arena.rs:1182:9
   7: <rapier2d::dynamics::rigid_body_set::RigidBodySet as core::ops::index::Index<rapier2d::dynamics::rigid_body_components::RigidBodyHandle>>::index
             at ./crates/rapier2d/../../src/dynamics/rigid_body_set.rs:234:10
   8: rapier_testbed2d::testbed::Testbed::update_character_controller
             at ./crates/rapier_testbed2d/../../src_testbed/testbed.rs:705:35
   9: rapier_testbed2d::testbed::update_testbed
             at ./crates/rapier_testbed2d/../../src_testbed/testbed.rs:1065:9
  10: core::ops::function::FnMut::call_mut
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/core/src/ops/function.rs:166:5
  11: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/core/src/ops/function.rs:297:13
  12: <Func as bevy_ecs::system::function_system::SystemParamFunction<(),Out,(F0,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12),()>>::run::call_inner
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.8.1/src/system/function_system.rs:564:21
  13: <Func as bevy_ecs::system::function_system::SystemParamFunction<(),Out,(F0,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12),()>>::run
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.8.1/src/system/function_system.rs:567:17
  14: <bevy_ecs::system::function_system::FunctionSystem<In,Out,Param,Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.8.1/src/system/function_system.rs:403:19
  15: bevy_ecs::system::system::System::run
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.8.1/src/system/system.rs:50:18
  16: <bevy_ecs::schedule::executor::SingleThreadedExecutor as bevy_ecs::schedule::executor::ParallelSystemExecutor>::run_systems
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.8.1/src/schedule/executor.rs:25:17
  17: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.8.1/src/schedule/stage.rs:884:17
  18: bevy_ecs::schedule::Schedule::run_once
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.8.1/src/schedule/mod.rs:342:13
  19: bevy_app::app::App::update
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.8.1/src/app.rs:119:9
  20: bevy_winit::winit_runner_with::{{closure}}
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.8.1/src/lib.rs:618:21
  21: winit::platform_impl::platform::sticky_exit_callback
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:753:5
  22: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/x11/mod.rs:293:17
  23: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/x11/mod.rs:392:9
  24: winit::platform_impl::platform::EventLoop<T>::run
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:669:56
  25: winit::event_loop::EventLoop<T>::run
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/event_loop.rs:154:9
  26: bevy_winit::run
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.8.1/src/lib.rs:240:5
  27: bevy_winit::winit_runner_with
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.8.1/src/lib.rs:663:9
  28: bevy_winit::winit_runner
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.8.1/src/lib.rs:280:5
  29: core::ops::function::Fn::call
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/core/src/ops/function.rs:78:5
  30: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/alloc/src/boxed.rs:1954:9
  31: bevy_app::app::App::run
             at /home/darth/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.8.1/src/app.rs:135:9
  32: rapier_testbed2d::testbed::TestbedApp::run_with_init
             at ./crates/rapier_testbed2d/../../src_testbed/testbed.rs:400:13
  33: rapier_testbed2d::testbed::TestbedApp::run
             at ./crates/rapier_testbed2d/../../src_testbed/testbed.rs:235:9
  34: all_examples2::main
             at ./examples2d/./all_examples2.rs:96:5
  35: core::ops::function::FnOnce::call_once
             at /rustc/4a14677239bbd9a3892d165ee24513c1a05820e4/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by sebcrozet** [comment]
Hi! The inputs to move the character are the arrow keys, not A or D. The A or D keys have other uses (it’s for removing rigid-bodies or joints).
