### ISSUE TITLE
Built app WASM issue after upgrading to 0.12.0

### ISSUE THREAD

**Issue by Noobulater** [dimforge/rapier#624]
After upgrading from ^0.11.2, and then building using vite build, the resulting app will encounter this issue when creating a new physics world.  Tested using https://github.com/viridia/demo-rapier-three

Steps to reproduce
1.) Install the repo https://github.com/viridia/demo-rapier-three
2.) Upgrade rapier to the latest version
3.) Build using `npm run build` 
4.) Serve the resulting `dist` directory and test the app

Resulting Behavior
rapier-be6a9884.js:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'rawintegrationparameters_new')
    at new tt (rapier-be6a9884.js:1:30250)
    at new Me (rapier-be6a9884.js:1:71843)
    at new Dt (rapier-be6a9884.js:1:100396)
    at mp.attach (index-4c621a1f.js:3191:107366)
tt @ rapier-be6a9884.js:1
Me @ rapier-be6a9884.js:1
Dt @ rapier-be6a9884.js:1
attach @ index-4c621a1f.js:3191
await in attach (async)
fp @ index-4c621a1f.js:3191
(anonymous) @ index-4c621a1f.js:3191

On Engine.ts line 90

` this.physicsWorld = new r.World(gravity);`

Expected Behavior
The physics world is created and physics works successfully

**Comment by Noobulater** [comment]
Still an issue with 0.13.1

**Comment by EyeOfMidas** [comment]
I am also having this issue. `vite build` works fine but when I try to view the built project, I get the same error ```Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'rawintegrationparameters_new')``` in the browser window.

**Comment by edimitchel** [comment]
I have fix the problem locally by having found the problem: **tree-shaking** from vite/rollup removes the function which initializes the wasm instance because not detected as used on execution thus not declared as having side effects.

The solution is to apply the `sideEffects` field in the rapier's `package.json` to '/*.js' (or something better). I tried to use more precise options (by using `rapier_wasm3d_bg.js` but it doesn't work)

**Comment by edimitchel** [comment]
Another solution which doesn't need a change from rapier is to disable tree shaking from the vite config.

```diff
// vite.config.ts
+  build: {
+    rollupOptions: {
+      treeshake: false,
+    }
+  }
```
